In [57]:
#Execute this cell if have problem with relative import
#.
import sys; sys.path.insert(0, '..')

In [58]:
from pprint import pprint

In [59]:
import pandas as pd
pd.set_option('display.max_columns', None)
pit_df = pd.read_csv("../Data/Corpus_csv/pitchers_all_career.csv")

In [60]:
pit_df.head()

,Id,Name,Active,First year,Last year,Url,Country,Bat hand,Throw hand,Full Name,HoF,HoF type,HoF year,HoF comittee,Player type,retirement_age,total_seasons,career_teams,career_leagues,first_position,second_position,play_in_mayors,play_in_negro_league,two_way_player,debut_decade,retirament_decade,W_pt,L_pt,W-L%_pt,ERA_pt,G_pt,GS_pt,GF_pt,CG_pt,SHO_pt,SV_pt,IP_pt,H_pt,R_pt,ER_pt,HR_pt,BB_pt,IBB_pt,SO_pt,HBP_pt,BK_pt,WP_pt,BF_pt,ERA+_pt,FIP_pt,WHIP_pt,H9_pt,HR9_pt,BB9_pt,SO9_pt,SO/W_pt,RAA_pt,WAA_pt,WAR_pt,RAR_pt
0,Jay_Aldrich_192,Jay Aldrich,False,1987,1990,https://www.baseball-reference.com//players/a/...,us,Right,Right,Jay Robert Aldrich,0,-,-,-,1,29,3,"['MIL', 'BAL']","['AL', 'NL']",P,-,1,0,0,1980,1990,6.0,5.0,0.545,4.72,62.0,0.0,21.0,0.0,0.0,2.0,108.2,119.0,62.0,57.0,12.0,39.0,9.0,46.0,3.0,2.0,3.0,474.0,90.0,4.57,1.454,9.9,1.0,3.2,3.8,1.18,-7.0,-0.7,-0.1,4.0
1,A.J._Achter_52,A.J. Achter,False,2014,2016,https://www.baseball-reference.com//players/a/...,us,Right,Right,Adam Joseph Achter,0,-,-,-,1,27,3,"['MIN', 'LAA']",['AL'],P,-,1,0,0,2010,2010,2.0,1.0,0.667,3.92,45.0,0.0,22.0,0.0,0.0,0.0,62.0,69.0,30.0,27.0,13.0,21.0,2.0,33.0,1.0,0.0,0.0,267.0,104.0,5.87,1.452,10.0,1.9,3.0,4.8,1.57,-2.0,-0.3,0.3,4.0
2,A.J._Alexy_214,A.J. Alexy,True,2021,2021,https://www.baseball-reference.com//players/a/...,us,Right,Right,Adam John Alexy,0,-,-,-,1,23,1,['TEX'],['AL'],P,-,1,0,0,2020,2020,3.0,1.0,0.750,4.70,5.0,4.0,0.0,0.0,0.0,0.0,23.0,13.0,12.0,12.0,4.0,17.0,0.0,17.0,1.0,0.0,0.0,97.0,95.0,6.30,1.304,5.1,1.6,6.7,6.7,1.00,-1.0,-0.1,0.1,1.0
3,Aaron_Ashby_601,Aaron Ashby,True,2021,2022,https://www.baseball-reference.com//players/a/...,us,Right,Left,Aaron Phillip Ashby,0,-,-,-,1,24,2,['MIL'],['NL'],P,-,1,0,0,2020,2020,3.0,5.0,0.375,3.70,23.0,8.0,5.0,0.0,0.0,2.0,65.2,51.0,35.0,27.0,6.0,32.0,0.0,78.0,2.0,0.0,3.0,281.0,113.0,3.52,1.264,7.0,0.8,4.4,10.7,2.44,-6.0,-0.6,-0.1,1.0
4,Abe_Alvarez_329,Abe Alvarez,False,2004,2006,https://www.baseball-reference.com//players/a/...,us,Left,Left,Abraham Alvarez,0,-,-,-,1,23,3,['BOS'],['AL'],P,-,1,0,0,2000,2000,0.0,1.0,0.000,11.32,4.0,1.0,1.0,0.0,0.0,0.0,10.1,19.0,13.0,13.0,5.0,7.0,0.0,5.0,0.0,0.0,0.0,53.0,46.0,10.43,2.516,16.5,4.4,6.1,4.4,0.71,-7.0,-0.6,-0.4,-5.0

In [61]:
pit_df.shape

(10157, 60)

In [44]:
from Preprocessing.data_keys import headers_bio, headers_pit

In [45]:
from Preprocessing.data_frame_procces import filter_dataset, select_features

In [46]:
pit_df['retirement_age'] = (
        pit_df['retirement_age'].replace('desconocido', pit_df['retirement_age'].mode()[0])
    )
pit_df['retirement_age'] = pit_df['retirement_age'].astype('int64')

In [47]:
gt_conditions = {
    
}
eq_conditions = {
    "HoF type":['-','Player'],
    'play_in_negro_league':[1]
}
filter_negro_league_df = filter_dataset(pit_df, eq_conditions,gt_conditions, None, None)

In [48]:
filter_negro_league_df.shape

(797, 60)

In [49]:
for h in headers_pit:
    nan = filter_negro_league_df[h].isna().any()
    if nan:
        print(f"{h}:{nan} --->{filter_negro_league_df[h].isna().sum()}")
        #print(f"{h}:{bat_df[h].isna().sum()}")

W-L%_pt:True --->167
ERA_pt:True --->7
GF_pt:True --->252
HR_pt:True --->120
IBB_pt:True --->499
BK_pt:True --->390
WP_pt:True --->9
BF_pt:True --->107
ERA+_pt:True --->51
FIP_pt:True --->130
WHIP_pt:True --->13
H9_pt:True --->13
HR9_pt:True --->130
BB9_pt:True --->13
SO9_pt:True --->13
SO/W_pt:True --->66
WAA_pt:True --->5
WAR_pt:True --->5

In [50]:
print(filter_negro_league_df['HoF'].value_counts())

0    788
1      9
Name: HoF, dtype: int64

In [51]:
features = ['retirement_age','total_seasons','play_in_mayors','play_in_negro_league','two_way_player'
            ,'W_pt','L_pt','W-L%_pt','ERA_pt','G_pt','GS_pt','GF_pt','CG_pt','SHO_pt','SV_pt',
            'IP_pt','H_pt','R_pt','ER_pt','HR_pt','BB_pt','SO_pt','BK_pt','WP_pt',
            'BF_pt','ERA+_pt','FIP_pt','WHIP_pt','H9_pt','HR9_pt','BB9_pt','SO9_pt','SO/W_pt',
            'RAA_pt','WAA_pt','WAR_pt','RAR_pt']
target = ['HoF']

print(len(features+target))

38

In [52]:
#temp=filter_negro_league_df.dropna()
#temp.reset_index(inplace=True, drop=True)

#X = select_features(temp, of_features)
#y = select_features(temp, ['HoF'])

In [54]:
filter_negro_league_df.describe()

,First year,Last year,HoF,Player type,retirement_age,total_seasons,play_in_mayors,play_in_negro_league,two_way_player,debut_decade,retirament_decade,W_pt,L_pt,W-L%_pt,ERA_pt,G_pt,GS_pt,GF_pt,CG_pt,SHO_pt,SV_pt,IP_pt,H_pt,R_pt,ER_pt,HR_pt,BB_pt,IBB_pt,SO_pt,HBP_pt,BK_pt,WP_pt,BF_pt,ERA+_pt,FIP_pt,WHIP_pt,H9_pt,HR9_pt,BB9_pt,SO9_pt,SO/W_pt,RAA_pt,WAA_pt,WAR_pt,RAR_pt
count,797.000000,797.000000,797.000000,797.0,797.000000,797.000000,797.000000,797.0,797.000000,797.000000,797.000000,797.000000,797.000000,630.000000,790.0000,797.000000,797.000000,545.000000,797.000000,797.000000,797.000000,797.000000,797.000000,797.000000,797.000000,677.000000,797.000000,298.000000,797.000000,797.000000,407.000000,788.000000,690.000000,746.000000,667.000000,784.000000,784.000000,667.000000,784.000000,784.000000,731.000000,797.000000,792.000000,792.000000,797.000000
mean,1933.583438,1936.745295,0.011292,1.0,27.811794,3.145546,0.051443,1.0,0.016311,1929.247177,1931.856964,9.693852,9.043915,0.409094,inf,29.348808,19.053952,4.970642,11.026349,1.057716,1.001255,163.251945,170.686324,94.951066,75.203262,6.366322,54.879548,0.607383,80.337516,4.461731,0.147420,1.818528,627.691304,91.454424,4.289175,1.885441,12.358036,0.508096,4.615689,3.961607,1.196019,3.362610,0.533586,1.846212,16.706399
std,8.823058,9.049924,0.105730,0.0,5.241860,3.288689,0.221038,0.0,0.126749,8.353700,8.656750,19.464479,15.051063,0.288437,NaN,50.227585,34.076301,9.123291,21.402591,2.717278,2.823314,292.951021,293.659268,153.133662,122.060004,14.843022,91.563488,3.920534,157.696452,7.885812,0.479004,3.825124,1058.907926,59.887780,2.905643,1.481718,9.585498,1.272153,6.040882,2.569552,0.892578,33.539937,3.294144,5.247619,53.343762
min,1920.000000,1920.000000,0.000000,1.0,16.000000,1.000000,0.000000,1.0,0.000000,1920.000000,1920.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,9.000000,-0.310000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-77.000000,-6.100000,-3.300000,-50.000000
25%,1925.000000,1929.000000,0.000000,1.0,26.000000,1.000000,0.000000,1.0,0.000000,1920.000000,1920.000000,0.000000,0.000000,0.177500,3.7225,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,6.000000,7.000000,6.000000,5.000000,0.000000,3.000000,0.000000,2.000000,0.000000,0.000000,0.000000,30.000000,61.000000,3.095000,1.326750,8.900000,0.000000,2.500000,2.700000,0.680000,-7.000000,-0.500000,-0.300000,-4.000000
50%,1934.000000,1938.000000,0.000000,1.0,26.000000,2.000000,0.000000,1.0,0.000000,1930.000000,1930.000000,1.000000,2.000000,0.457500,4.8000,7.000000,4.000000,2.000000,1.000000,0.000000,0.000000,31.000000,38.000000,25.000000,19.000000,2.000000,14.000000,0.000000,13.000000,1.000000,0.000000,0.000000,154.500000,88.000000,3.600000,1.509000,10.050000,0.200000,3.400000,3.900000,1.080000,-2.000000,-0.100000,0.100000,0.000000
75%,1941.000000,1945.000000,0.000000,1.0,30.000000,4.000000,0.000000,1.0,0.000000,1940.000000,1940.000000,10.000000,10.000000,0.573250,7.1250,35.000000,20.000000,6.000000,10.000000,1.000000,1.000000,175.000000,187.000000,113.000000,88.000000,7.000000,65.000000,0.000000,82.000000,5.000000,0.000000,2.000000,718.000000,110.000000,4.385000,1.890000,12.500000,0.500000,4.900000,5.000000,1.575000,2.000000,0.300000,1.200000,9.000000
max,1948.000000,1965.000000,1.000000,1.0,58.000000,21.000000,1.000000,1.0,1.000000,1940.000000,1960.000000,153.000000,104.000000,1.000000,inf,398.000000,305.000000,114.000000,145.000000,31.000000,44.000000,2251.200000,2188.000000,1007.000000,893.000000,255.000000,840.000000,40.000000,1480.000000,60.000000,5.000000,45.000000,9320.000000,911.000000,32.690000,18.000000,108.000000,13.500000,108.000000,20.300000,9.000000,336.000000,33.900000,47.600000,455.000000

In [55]:
pit_df['W-L%_pt'] = (
        pit_df['W-L%_pt'].replace(nan, 0.409094)
    )
pit_df['W-L%_pt'] = pit_df['W-L%_pt'].astype('int64')

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer

In [53]:


for h in features:
    nan = filter_negro_league_df[h].isna().any()
    if nan:
        print(f"{h}:{nan} --->{filter_negro_league_df[h].isna().sum()}")
        #print(f"{h}:{bat_df[h].isna().sum()}")

W-L%_pt:True --->167
ERA_pt:True --->7
GF_pt:True --->252
HR_pt:True --->120
BK_pt:True --->390
WP_pt:True --->9
BF_pt:True --->107
ERA+_pt:True --->51
FIP_pt:True --->130
WHIP_pt:True --->13
H9_pt:True --->13
HR9_pt:True --->130
BB9_pt:True --->13
SO9_pt:True --->13
SO/W_pt:True --->66
WAA_pt:True --->5
WAR_pt:True --->5